# Generated by Django 4.0.6 on 2022-08-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_srticle_image_alter_article_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='srticle_image',
            new_name='article_image',
        ),
    ]
